"""Initial migration.

Revision ID: 2a99c0e92c8d
Revises: 
Create Date: 2024-11-23 10:59:58.961833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a99c0e92c8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mineral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('reserve_size', sa.Float(), nullable=False),
    sa.Column('extraction_cost', sa.Float(), nullable=False),
    sa.Column('carbon_emissions', sa.Float(), nullable=True),
    sa.Column('water_usage', sa.Float(), nullable=True),
    sa.Column('land_degradation', sa.Float(), nullable=True),
    sa.Column('rehabilitation_efforts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mineral')
    # ### end Alembic commands ###
